### ISSUE TITLE
Spawn flag not working.

### ISSUE THREAD

**Issue by Tenelia** [Arckenver/Nations#125]
[21:57:58 ERROR] [Sponge]: Could not pass SpawnEntityEvent$Spawner$Impl to Plugin{id=nations, name=Nations, version=2.4, description=A towny-like worldguard-like zone managment plugin., url=https://github.com/Arckenver/Nations, authors=[Arckenver], source=mods\Nations-2.4.jar}
java.lang.NoSuchMethodError: org.spongepowered.api.event.entity.SpawnEntityEvent.getTargetWorld()Lorg/spongepowered/api/world/World;
        at com.arckenver.nations.listener.MobSpawningListener.onEntitySpawn(MobSpawningListener.java:17) ~[MobSpawningListener.class:2.4]
        at org.spongepowered.common.event.listener.SpawnEntityEventListener_MobSpawningListener_onEntitySpawn236.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-6.0.0-BETA-249]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305) [SpongeEventManager.class:1.11.2-6.0.0-BETA-249]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:319) [SpongeEventManager.class:1.11.2-6.0.0-BETA-249]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:133) [SpongeImpl.class:1.11.2-6.0.0-BETA-249]
        at org.spongepowered.common.event.tracking.phase.generation.GeneralGenerationPhaseState.unwind(GeneralGenerationPhaseState.java:113) [GeneralGenerationPhaseState.class:1.11.2-6.0.0-BETA-249]
        at org.spongepowered.common.event.tracking.phase.generation.GenerationPhase.unwind(GenerationPhase.java:101) [GenerationPhase.class:1.11.2-6.0.0-BETA-249]
        at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:222) [CauseTracker.class:1.11.2-6.0.0-BETA-249]
        at net.minecraft.world.WorldEntitySpawner.func_77192_a(SourceFile:797) [ajz.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(SourceFile:198) [lw.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1563) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:335) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:562) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:466) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by yepidoodles** [comment]
Context?

**Comment by Tenelia** [comment]
I turned off mob spawn to false, but creepers, zombies, and etc kept spawning.

**Comment by yepidoodles** [comment]
Which version of Sponge are you using?

**Comment by Tenelia** [comment]
1.11.2-6.0.0-BETA-249

**Comment by yepidoodles** [comment]
That will be why, the current version of Nations isn't completely compatible with API 6.0.0/ MC 1.11.2

**Comment by Tenelia** [comment]
Yup, I understand. Just thought to let you know the bug/incompatibility exists. (: Hope it helps you a little.

**Comment by yepidoodles** [comment]
https://github.com/Arckenver/Nations/pull/123

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
