### ISSUE TITLE
Console Spam Error

### ISSUE THREAD

**Issue by BreeOge** [Arckenver/Nations#129]
My console is getting spammed with this..

Could not pass SpawnEntityEvent$Spawner$Impl to Plugin{id=nations, name=Nations, version=2.4, description=A towny-like worldguard-like zone managment plugin., url=https://github.com/Arckenver/Nations, authors=[Arckenver], source=/home/AMP/.ampdata/instances/MCMA/Minecraft/mods/Nations-2.4.jar}
Console 05/04/2017 00:13:51
00:13:51java.lang.NoSuchMethodError: org.spongepowered.api.event.entity.SpawnEntityEvent.getTargetWorld()Lorg/spongepowered/api/world/World;
at com.arckenver.nations.listener.MobSpawningListener.onEntitySpawn(MobSpawningListener.java:17) ~[MobSpawningListener.class:2.4]
at org.spongepowered.common.event.listener.SpawnEntityEventListener_MobSpawningListener_onEntitySpawn126.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) [SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) [SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) [SpongeImpl.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.phase.generation.GenerationPhase.spawnEntityOrCapture(GenerationPhase.java:142) [GenerationPhase.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.CauseTracker.spawnEntity(CauseTracker.java:636) [CauseTracker.class:1.11.2-2282-7.0.0-BETA-2301]
at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:2668) [lw.class:?]
at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:775) [ajz.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:197) [lw.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
00:14:02 at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) ~[SpongeImpl.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:624) ~[TrackingUtil.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:531) ~[TrackingUtil.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.lambda$processPostTick$1(BlockTickPhaseState.java:85) ~[BlockTickPhaseState.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) [CapturedSupplier.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.processPostTick(BlockTickPhaseState.java:85) [BlockTickPhaseState.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.phase.tick.TickPhase.unwind(TickPhase.java:68) [TickPhase.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:222) [CauseTracker.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:298) [TrackingUtil.class:1.11.2-2282-7.0.0-BETA-2301]
at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2114) [lw.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:219) [lw.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Server thread/ERROR - Sponge 05/04/2017 00:14:02
00:14:02Could not pass ChangeBlockEvent$Post$Impl to Plugin{id=nations, name=Nations, version=2.4, description=A towny-like worldguard-like zone managment plugin., url=https://github.com/Arckenver/Nations, authors=[Arckenver], source=/home/AMP/.ampdata/instances/MCMA/Minecraft/mods/Nations-2.4.jar}
Console 05/04/2017 00:14:02
00:14:02java.lang.NoSuchMethodError: org.spongepowered.api.event.block.ChangeBlockEvent.getTargetWorld()Lorg/spongepowered/api/world/World;
at com.arckenver.nations.listener.FireListener.onFire(FireListener.java:20) ~[FireListener.class:2.4]
at org.spongepowered.common.event.listener.ChangeBlockEventListener_FireListener_onFire124.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345) ~[SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) ~[SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) ~[SpongeImpl.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.TrackingUtil.throwMultiEventsAndCreatePost(TrackingUtil.java:834) ~[TrackingUtil.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:533) ~[TrackingUtil.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.lambda$processPostTick$1(BlockTickPhaseState.java:85) ~[BlockTickPhaseState.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) [CapturedSupplier.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.processPostTick(BlockTickPhaseState.java:85) [BlockTickPhaseState.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.phase.tick.TickPhase.unwind(TickPhase.java:68) [TickPhase.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:222) [CauseTracker.class:1.11.2-2282-7.0.0-BETA-2301]
at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:298) [TrackingUtil.class:1.11.2-2282-7.0.0-BETA-2301]
at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2114) [lw.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:219) [lw.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by TheoKah** [comment]
What version of sponge are you on?

**Comment by BreeOge** [comment]
spongeforge-1.11.2-2282-7.0.0-BETA-2301

**Comment by BreeOge** [comment]
Im dropping back to 1.11.2-2282-6.0.0-BETA-2297 to see if I still get errors..

**Comment by BreeOge** [comment]
Same issue with 1.11.2-2282-6.0.0-BETA-2297, exact same errors..

**Comment by yepidoodles** [comment]
It's the 6.0.0 version, Nations hasn't been designed to work with 6.0.0 yet. 

https://github.com/Arckenver/Nations/pull/123

https://github.com/Arckenver/Nations/issues/125

**Comment by BreeOge** [comment]
Ahh, ok.. thank you..

**Comment by TheoKah** [comment]
I'll see what I can do next week. I need to compile it for 6.0.0 and see if everything is still working on 1.10.2_5.2.0
