### ISSUE TITLE
Anti-Break not working 1.10

### ISSUE THREAD

**Issue by tenten8401** [Arckenver/Nations#16]
Trying to break blocks (claimed or unclaimed) on 1.10 yields this error:

```
[02:01:34] [Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Primary$MainHand$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@1231c091
java.lang.NoSuchMethodError: org.spongepowered.api.entity.living.player.Player.getItemInHand()Ljava/util/Optional;
at com.arckenver.nations.listener.GoldenAxeListener.onPlayerLeftClick(GoldenAxeListener.java:56) ~[GoldenAxeListener.class:0.10]
at org.spongepowered.common.event.listener.PrimaryListener_GoldenAxeListener_onPlayerLeftClick65.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2044-5.0.0-BETA-1661]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:349) [SpongeModEventManager.class:1.10.2-2044-5.0.0-BETA-1661]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:332) [SpongeModEventManager.class:1.10.2-2044-5.0.0-BETA-1661]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:377) [SpongeModEventManager.class:1.10.2-2044-5.0.0-BETA-1661]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:362) [SpongeModEventManager.class:1.10.2-2044-5.0.0-BETA-1661]
at net.minecraft.server.MinecraftServer.handler$onServerTickEnd$0(MinecraftServer.java:565) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:658) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
```

Thinking this has something to do with the fact that players now dual wield.

**Comment by Arckenver** [comment]
Indeed. It's due to the fact that Nations 0.x versions are targeting v4.x.x of SpongeAPI.

To use minecraft 1.10.2 compatible versions of SpongeForge/SpongeVanilla (SpongeAPI v5.x.x), please wait for versions 2.x of Nations. Those will be out when SpongeAPI v5.x.x won't be `bleeding` anymore (at the same time as v1.x of Nations).

**Comment by tenten8401** [comment]
Can't wait until it's updated! Might fork it and give it a shot myself, although I doubt I'll get far as I'm fairly new to this whole sponge thing.

**Comment by Arckenver** [comment]
Can't wait too ! Thanks for your interest in Nations.
