### ISSUE TITLE
Cannot find file specified : \C

### ISSUE THREAD

**Issue by FriedSkrimp** [Arckenver/Nations#166]
I'm running spongeforge: spongeforge-1.10.2-2281-5.2.0-BETA-2555
My minecraft version is 1.10.2
Nations can't seem to find my C drive, is there any way I can fix this?
Also, my C drive is listed as C:(Backslash), not \C. 
Please respond, I'm trying hard to get this to work.

**Comment by FriedSkrimp** [comment]
Here's what command prompt is saying:

`[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at java.lang.reflect.Method.invoke(Unknown Sourc
e)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.EventSubscriber.ha
ndleEvent(EventSubscriber.java:74)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.SynchronizedEventS
ubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.EventBus.dispatch(
EventBus.java:322)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.EventBus.dispatchQ
ueuedEvents(EventBus.java:304)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.EventBus.post(Even
tBus.java:275)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at net.minecraftforge.fml.common.LoadController.
redirect$onPost$zzb000(LoadController.java:561)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at net.minecraftforge.fml.common.LoadController.
distributeStateMessage(LoadController.java:145)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at net.minecraftforge.fml.common.Loader.serverSt
arted(Loader.java:868)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at net.minecraftforge.fml.common.FMLCommonHandle
r.handleServerStarted(FMLCommonHandler.java:297)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at net.minecraft.server.MinecraftServer.run(Mine
craftServer.java:433)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at java.lang.Thread.run(Unknown Source)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]: java.io.FileNotFoundException: \C (The system cannot fin
d the file specified)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at java.util.zip.ZipFile.open(Native Method)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at java.util.zip.ZipFile.<init>(Unknown Source)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at java.util.zip.ZipFile.<init>(Unknown Source)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at java.util.jar.JarFile.<init>(Unknown Source)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at java.util.jar.JarFile.<init>(Unknown Source)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.arckenver.nations.cmdexecutor.NationCmds.
createCmds(NationCmds.java:59)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.arckenver.nations.cmdexecutor.NationCmds.
create(NationCmds.java:47)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.arckenver.nations.NationsPlugin.onStart(N
ationsPlugin.java:79)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at org.spongepowered.common.event.listener.GameS
tartedServerEventListener_NationsPlugin_onStart6.handle(Unknown Source)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at org.spongepowered.common.event.RegisteredList
ener.handle(RegisteredListener.java:95)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at org.spongepowered.mod.event.SpongeModEventMan
ager.post(SpongeModEventManager.java:313)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at org.spongepowered.mod.event.SpongeModEventMan
ager.post(SpongeModEventManager.java:342)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at org.spongepowered.mod.SpongeMod.onStateEvent(
SpongeMod.java:234)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(
Native Method)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at sun.reflect.NativeMethodAccessorImpl.invoke(U
nknown Source)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at sun.reflect.DelegatingMethodAccessorImpl.invo
ke(Unknown Source)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at java.lang.reflect.Method.invoke(Unknown Sourc
e)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.EventSubscriber.ha
ndleEvent(EventSubscriber.java:74)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.SynchronizedEventS
ubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.EventBus.dispatch(
EventBus.java:322)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.EventBus.dispatchQ
ueuedEvents(EventBus.java:304)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.EventBus.post(Even
tBus.java:275)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at net.minecraftforge.fml.common.LoadController.
sendEventToModContainer(LoadController.java:243)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at net.minecraftforge.fml.common.LoadController.
propogateStateMessage(LoadController.java:221)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(
Native Method)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at sun.reflect.NativeMethodAccessorImpl.invoke(U
nknown Source)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at sun.reflect.DelegatingMethodAccessorImpl.invo
ke(Unknown Source)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at java.lang.reflect.Method.invoke(Unknown Sourc
e)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.EventSubscriber.ha
ndleEvent(EventSubscriber.java:74)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.SynchronizedEventS
ubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.EventBus.dispatch(
EventBus.java:322)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.EventBus.dispatchQ
ueuedEvents(EventBus.java:304)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at com.google.common.eventbus.EventBus.post(Even
tBus.java:275)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at net.minecraftforge.fml.common.LoadController.
redirect$onPost$zzb000(LoadController.java:561)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at net.minecraftforge.fml.common.LoadController.
distributeStateMessage(LoadController.java:145)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at net.minecraftforge.fml.common.Loader.serverSt
arted(Loader.java:868)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at net.minecraftforge.fml.common.FMLCommonHandle
r.handleServerStarted(FMLCommonHandler.java:297)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at net.minecraft.server.MinecraftServer.run(Mine
craftServer.java:433)
[22:30:58] [Server thread/INFO] [STDERR]: [com.arckenver.nations.cmdexecutor.Nat
ionCmds:createCmds:77]:         at java.lang.Thread.run(Unknown Source)`

**Comment by FriedSkrimp** [comment]
Update:
2.5 and 2.6 both work, but 2.7 continues to give me the errors listed above.

**Comment by TheoKah** [comment]
I see what it is. I'll fix it next week end

**Comment by TheoKah** [comment]
Fixed: https://github.com/Arckenver/Nations/releases/tag/v2.8
