### ISSUE TITLE
[1.12.2] Error when killing a mob while doMobLoot is "false"

### ISSUE THREAD

**Issue by xhatz** [Arckenver/Nations#177]
Hello!

When I am killing a mob while the gamerule doMobLoot is set to false, I get this error code:
(This is in a **server's console**, by the way)
EDIT2: Only when the kill is a playerKill.

`[18:18:12] [Server thread/ERROR] [Sponge]: Could not pass DropItemEvent$Destruct$Impl to Plugin{id=nations, name=Nations, version=2.9-S7.0-MC1.12.1-hotfix1, description=A towny-like worldguard-like zone managment plugin, url=https://github.com/Arckenver/Nations, authors=[Arckenver, Carrot], source=A:\PATH_TO_PLUGIN\Nations-2.9-S7.0-MC1.12.1-hotfix1.jar}
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_121]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_121]
        at com.arckenver.nations.listener.BuildPermListener.onEntitySpawn(BuildPermListener.java:111) ~[BuildPermListener.class:?]
        at org.spongepowered.common.event.listener.SpawnEntityEventListener_BuildPermListener_onEntitySpawn112.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2529-7.0.0-BETA-2747]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:316) [SpongeModEventManager.class:1.12.2-2529-7.0.0-BETA-2747]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:282) [SpongeModEventManager.class:1.12.2-2529-7.0.0-BETA-2747]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345) [SpongeModEventManager.class:1.12.2-2529-7.0.0-BETA-2747]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:333) [SpongeModEventManager.class:1.12.2-2529-7.0.0-BETA-2747]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:198) [SpongeImpl.class:1.12.2-2529-7.0.0-BETA-2747]
        at org.spongepowered.common.event.tracking.phase.entity.DeathPhase.unwind(DeathPhase.java:131) [DeathPhase.class:1.12.2-2529-7.0.0-BETA-2747]
        at org.spongepowered.common.event.tracking.phase.entity.DeathPhase.unwind(DeathPhase.java:51) [DeathPhase.class:1.12.2-2529-7.0.0-BETA-2747]
        at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:229) [PhaseTracker.class:1.12.2-2529-7.0.0-BETA-2747]
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:399) [PhaseContext.class:1.12.2-2529-7.0.0-BETA-2747]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3531) [vp.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70) [ade.class:?]
        at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:233) [adt.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:3902) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1420) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:2588) [pa.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) [li.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) [li.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-2529-7.0.0-BETA-2747]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zke000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2529-7.0.0-BETA-2747]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zig000(MinecraftServer.java:4008) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]`

Thank you!

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
