### ISSUE TITLE
Could not pass DropItemEvent$Destruct

### ISSUE THREAD

**Issue by RaiKave** [Arckenver/Nations#184]
Could not pass DropItemEvent$Destruct$Impl to Plugin{id=nations, name=Nations, version=2.9-S7.0-MC1.12.1-hotfix1, description=A towny-like worldguard-like zone managment plugin, url=https://github.com/Arckenver/Nations, authors=[Arckenver, Carrot], source=/data/service10072/data/service_item_719384/mods/Plugin - Nations-2.9-S7.0.jar}
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_45-internal]
at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_45-internal]
at com.arckenver.nations.listener.BuildPermListener.onEntitySpawn(BuildPermListener.java:111) ~[BuildPermListener.class:?]
at org.spongepowered.common.event.listener.SpawnEntityEventListener_BuildPermListener_onEntitySpawn149.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:369) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:403) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:391) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:442) [SpongeEventManager.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.common.event.tracking.phase.entity.DeathPhase.unwind(DeathPhase.java:128) [DeathPhase.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.common.event.tracking.phase.entity.DeathPhase.unwind(DeathPhase.java:52) [DeathPhase.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:212) [PhaseTracker.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:392) [PhaseContext.class:1.12.2-2655-7.1.0-BETA-3065]
at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3536) [vp.class:?]
at com.lycanitesmobs.core.entity.EntityCreatureBase.func_70097_a(EntityCreatureBase.java:2745) [EntityCreatureBase.class:?]
at com.lycanitesmobs.core.entity.EntityCreatureTameable.func_70097_a(EntityCreatureTameable.java:479) [EntityCreatureTameable.class:?]
at mekanism.common.item.ItemAtomicDisassembler.func_77644_a(ItemAtomicDisassembler.java:76) [ItemAtomicDisassembler.class:?]
at net.minecraft.item.ItemStack.func_77961_a(ItemStack.java:366) [aip.class:?]
at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:3987) [aed.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1420) [oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:2605) [pa.class:?]
at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) [li.class:?]
at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) [li.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:150) [PacketUtil.class:1.12.2-2655-7.1.0-BETA-3065]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.clas
s:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:277) [SpongeImplHooks.class:1.12.2-2655-7.1.0-BETA-3065]
at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3975) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by Routhinator** [comment]
I'm getting this as well with the latest Nations and Sponge, every time a player dies.

**Comment by TheoKah** [comment]
Is it still a problem with https://github.com/Arckenver/Nations/releases/tag/v2.11_api7 ?

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
