### ISSUE TITLE
Upkeep not running

### ISSUE THREAD

**Issue by treyzania** [Arckenver/Nations#187]
You need to schedule the task to run on the main thread.  This exception gets thrown every day at midnight UTC on my server.

```
[12:00:00 ERROR] [Sponge]: The Scheduler tried to run the task nations-A-91 owned by Plugin{id=nations, name=Nations, version=2.9-S7.0-MC1.12.1, description=A towny-like worldguard-like zone managment plugin, url=https://github.com/Arckenver/Nations, authors=[Arckenver, Carrot], source=mods/Nations-2.9-S7.0-MC1.12.1.jar}, but an error occured.
java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=pool-3-thread-252, priority=5, group=java.lang.ThreadGroup[name=main,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=java.lang.ThreadGroup[name=main,maxpri=10]}')!
        at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:71) ~[SpongeCauseStackManager.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.event.SpongeCauseStackManager.getCurrentCause(SpongeCauseStackManager.java:85) ~[SpongeCauseStackManager.class:1.12.2-7.1.0-BETA-33]
        at com.arckenver.nations.NationsPlugin.getCause(NationsPlugin.java:145) ~[NationsPlugin.class:?]
        at com.arckenver.nations.task.TaxesCollectRunnable.run(TaxesCollectRunnable.java:68) ~[TaxesCollectRunnable.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-7.1.0-BETA-33]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by TheoKah** [comment]
Fixed: https://github.com/Arckenver/Nations/releases/tag/v2.11_api7
