### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by Takkapi** [Arckenver/Nations#207]
Could not load 'plugins\Nations-2.11-S7.0-MC1.12.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
