### ISSUE TITLE
Can't create nations

### ISSUE THREAD

**Issue by GershonR** [Arckenver/Nations#33]
```
08.10 12:35:19 [Server] Server thread/INFO [io.github.hsyyid.essentialcmds]: [Yuzuru] executed command n create Magnolia
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: org.h2.jdbc.JdbcSQLException: Value too long for column "ID VARCHAR(36)": "'nation-1ba2bbf2-173e-472f-af6f-f3e2e9bae0d8' (43)"; SQL statement:
08.10 12:35:19 [Server] INFO INSERT INTO economylitevirts (`id`, `balance`, `currency`) VALUES (?, ?, ?) [22001-192]
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.h2.message.DbException.get(DbException.java:179)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.h2.table.Column.validateConvertUpdateSequence(Column.java:335)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.h2.table.Table.validateConvertUpdateSequence(Table.java:784)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.h2.command.dml.Insert.insertRows(Insert.java:151)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.h2.command.dml.Insert.update(Insert.java:114)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.h2.command.CommandContainer.update(CommandContainer.java:98)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.h2.command.Command.executeUpdate(Command.java:258)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at io.github.flibio.economylite.utils.sql.SqlManager.executeUpdate(SqlManager.java:118)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at io.github.flibio.economylite.impl.VirtualServiceCommon.setBalance(VirtualServiceCommon.java:77)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at io.github.flibio.economylite.impl.economy.LiteEconomyService.getOrCreateAccount(LiteEconomyService.java:81)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at com.arckenver.nations.cmdexecutor.nation.NationCreateExecutor.execute(NationCreateExecutor.java:111)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:177)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:331)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:279)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at net.minecraft.util.Util.func_181617_a(SourceFile:44)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
08.10 12:35:19 [Server] Server thread/INFO [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:     at java.lang.Thread.run(Thread.java:745)
08.10 12:35:19 [Server] Server thread/ERROR [economylite]: Value too long for column "ID VARCHAR(36)": "'nation-1ba2bbf2-173e-472f-af6f-f3e2e9bae0d8' (43)"; SQL statement:
08.10 12:35:19 [Server] INFO INSERT INTO economylitevirts (`id`, `balance`, `currency`) VALUES (?, ?, ?) [22001-192]
08.10 12:35:19 [Server] Server thread/ERROR [com.arckenver.nations]: Could not create nation's account on the economy service !
```

**Comment by GershonR** [comment]
All good, just needed to update econonmylite
