### ISSUE TITLE
NA Delete Glitches Nation

### ISSUE THREAD

**Issue by GershonR** [Arckenver/Nations#37]
Error:

```
`
5.10 11:28:03 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'na delete Lol' for source EntityPlayerMP['NinjaMonkey'/58935, l='world', x=173.29, y=95.00, z=132.74]: null
15.10 11:28:03 [Server] INFO java.util.ConcurrentModificationException
15.10 11:28:03 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_92]
15.10 11:28:03 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1471) ~[?:1.8.0_92]
15.10 11:28:03 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1469) ~[?:1.8.0_92]
15.10 11:28:03 [Server] INFO at com.arckenver.nations.DataHandler.removeNation(DataHandler.java:162) ~[DataHandler.class:0.10]
15.10 11:28:03 [Server] INFO at com.arckenver.nations.cmdexecutor.nationadmin.NationadminDeleteExecutor.execute(NationadminDeleteExecutor.java:33) ~[NationadminDeleteExecutor.class:0.10]
15.10 11:28:03 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:177) ~[ChildCommandElementExecutor.class:1.8.9-1890-4.2.0-BETA-1762]
15.10 11:28:03 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:331) ~[CommandSpec.class:1.8.9-1890-4.2.0-BETA-1762]
15.10 11:28:03 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1890-4.2.0-BETA-1762]
15.10 11:28:03 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:279) [SpongeCommandManager.class:1.8.9-1890-4.2.0-BETA-1762]
15.10 11:28:03 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [bd.class:?]
15.10 11:28:03 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815) [lm.class:?]
15.10 11:28:03 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794) [lm.class:?]
15.10 11:28:03 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
15.10 11:28:03 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
15.10 11:28:03 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1762]
15.10 11:28:03 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
15.10 11:28:03 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
15.10 11:28:03 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
15.10 11:28:03 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
15.10 11:28:03 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
15.10 11:28:03 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
15.10 11:28:03 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
15.10 11:28:03 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
15.10 11:28:03 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
15.10 11:28:03 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
`
```

Steps to reproduce:
1. Make a nation
2. Deposit and claim land
3. Invite a player
4. Run /n leave and it will tell you need to resign
5. Run /na delete [the nation you made]
6. You will get a error running command: null
7. The land claims will remain

**Comment by Arckenver** [comment]
Thanks for reporting !
