### ISSUE TITLE
Tax Error

### ISSUE THREAD

**Issue by GershonR** [Arckenver/Nations#43]
On 1.10 Version

```
[12:00:11] [pool-2-thread-1/ERROR] [Sponge/sponge]: The Scheduler tried to run the task nations-A-8 owned by Plugin{id=nations, name=Nations, version=2.0, description=A towny-like worldguard-like zone managment plugin., url=https://github.com/Arckenver/Nations, authors=[Arckenver], source=L:\Programs\testserver\mods\Nations-2.0.jar}, but an error occured.
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_66]
    at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_66]
    at com.arckenver.nations.task.TaxesCollectRunnable.run(TaxesCollectRunnable.java:49) ~[TaxesCollectRunnable.class:2.0]
    at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2107-6.0.0-BETA-1856]
    at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.10.2-2107-6.0.0-BETA-1856]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_66]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_66]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

**Comment by Arckenver** [comment]
Thanks for reporting !
