### ISSUE TITLE
Error with PlayerTeleportEvent

### ISSUE THREAD

**Issue by Arckenver** [Arckenver/Nations#53]
Adnan got this error when using `/n spawn` command.

```plain
[23:23:00 ERROR] [Sponge]: Error occurred while executing command 'n spawn home' for source EntityPlayerMP['Adnan_'/26, l='world', x=211.52, y=66.00, z=-639.64]: com.arckenver.nations.event.PlayerTeleportEvent cannot be cast to org.spongepowered.api.event.impl.AbstractEvent
java.lang.ClassCastException: com.arckenver.nations.event.PlayerTeleportEvent cannot be cast to org.spongepowered.api.event.impl.AbstractEvent
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:313) ~[SpongeEventManager.class:1.10.2-5.1.0-BETA-355]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320) ~[SpongeEventManager.class:1.10.2-5.1.0-BETA-355]
        at com.arckenver.nations.cmdexecutor.nation.NationSpawnExecutor.execute(NationSpawnExecutor.java:56) ~[NationSpawnExecutor.class:2.1]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:179) ~[ChildCommandElementExecutor.class:1.10.2-5.1.0-BETA-355]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:351) ~[CommandSpec.class:1.10.2-5.1.0-BETA-355]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-5.1.0-BETA-355]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) [SpongeCommandManager.class:1.10.2-5.1.0-BETA-355]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:82) [bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:825) [me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:812) [me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:123) [PacketUtil.class:1.10.2-5.1.0-BETA-355]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zio000(SourceFile:39) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:140) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:338) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by vectrixdevelops** [comment]
Any update on this?

**Comment by Arckenver** [comment]
Still searching... I find this error odd and don't know where it comes from.

**Comment by TheoKah** [comment]
Looks like this error is only present on spongevanilla

**Comment by Arckenver** [comment]
Cf [this post in sponge forums](https://forums.spongepowered.org/t/error-with-custom-event/15832).

**Comment by Arckenver** [comment]
Should be now fixed. Fix will be available in the next release.
