### ISSUE TITLE
Null pointer in console after updating to sponge 1930 from 1888 ChangeBlockEvent

### ISSUE THREAD

**Issue by ProsperCraft** [Arckenver/Nations#68]
[10:21:38] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Break$Impl to Plugin{id=nations, name=Nations, version=2.2, description=A towny-like worldguard-like zone managment plugin., url=https://github.com/Arckenver/Nations, authors=[Arckenver], source=/opt/infinitylite/./plugins/Nations-2.2.jar}
java.lang.NullPointerException
        at net.minecraft.entity.player.EntityPlayerMP.func_145747_a(EntityPlayerMP.java:1092) ~[lu.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.sendMessage(EntityPlayerMP.java:54) ~[lu.class:?]
        at com.arckenver.nations.listener.BuildPermListener.lambda$null$61(BuildPermListener.java:57) ~[BuildPermListener.class:2.2]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_111]
        at com.arckenver.nations.listener.BuildPermListener.lambda$onPlayerBreaksBlock$62(BuildPermListener.java:53) ~[BuildPermListener.class:2.2]
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_111]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_111]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_111]
        at com.arckenver.nations.listener.BuildPermListener.onPlayerBreaksBlock(BuildPermListener.java:53) ~[BuildPermListener.class:2.2]
        at org.spongepowered.common.event.listener.BreakListener_BuildPermListener_onPlayerBreaksBlock220.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2171-5.1.0-BETA-1930]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357) [SpongeModEventManager.class:1.10.2-2171-5.1.0-BETA-1930]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) [SpongeModEventManager.class:1.10.2-2171-5.1.0-BETA-1930]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:121) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:94) [EventBus.class:?]
        at com.raoulvdberge.refinedstorage.tile.TileDestructor.updateNode(TileDestructor.java:149) [TileDestructor.class:?]
        at com.raoulvdberge.refinedstorage.tile.TileNode.func_73660_a(TileNode.java:79) [TileNode.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:211) [TrackingUtil.class:1.10.2-2171-5.1.0-BETA-1930]
        at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjk000(WorldServer.java:1298) [ls.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1282) [aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:713) [ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by TheoKah** [comment]
This is due to mods placing blocks using fake players.

This is fixed on the dev branch and will be merged asap

**Comment by TheoKah** [comment]
Fixed in #77
